language: bash
  
env:
  global:
    - RHYME=rhyme.txt

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

script:
  - bats tests/

notifications:
  email: false
